name: CI/CD

on:
  push:
    branches: [ main, stage, beta ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main, stage, beta ]

env:
  # github.repository as <account>/<repo>
  REGISTRY_NAME: macnev


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Setup Docker Image Tags
        run: |
          if [ ${GITHUB_REF_SLUG} == "main" ] ; then
            echo "NUCLEUS_TAGS=${REGISTRY_NAME}/github-actions-docker-sample:latest","${REGISTRY_NAME}/github-actions-docker-sample:prod" >> $GITHUB_ENV
            echo "SYNAPSE_TAGS=${REGISTRY_NAME}/github-actions-docker-sample:latest","${REGISTRY_NAME}/github-actions-docker-sample:prod" >> $GITHUB_ENV
          elif [ startsWith(${GITHUB_REF_SLUG}, 'v')] ; then
            echo "NUCLEUS_TAGS="${REGISTRY_NAME}/github-actions-docker-sample:${GITHUB_REF_SLUG:1}" >> $GITHUB_ENV
            echo "SYNAPSE_TAGS="${REGISTRY_NAME}/github-actions-docker-sample:${GITHUB_REF_SLUG:1}" >> $GITHUB_ENV
          else
            echo "NUCLEUS_TAGS=${REGISTRY_NAME}/github-actions-docker-sample:${GITHUB_REF_SLUG}" >> $GITHUB_ENV
            echo "SYNAPSE_TAGS=${REGISTRY_NAME}/github-actions-docker-sample:${GITHUB_REF_SLUG}" >> $GITHUB_ENV
          fi
          
      - name: Checkout
        uses: actions/checkout@v2.4.0
        
      - name: Print Env
        run: |
          echo "${{ env.NUCLEUS_TAGS }}"
          echo "${{ env.SYNAPSE_TAGS }}"

      - name: Docker Login
        uses: docker/login-action@v1.13.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          logout: true
    
      - name: Build and push Docker images
        if: ${{ github.ref == 'refs/heads/stage' || github.ref == 'refs/heads/beta' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }}
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          tags: ${{ env.NUCLEUS_TAGS }}
          file: build/Dockerfile.test
          push: true
