name: CI/CD

on:
  push:
    branches: [ main, stage, beta ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main, stage, beta ]

env:
  # github.repository as <account>/<repo>
  REGISTRY_NAME: macnev


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: set-env
        run: |
          if [[ ${GITHUB_REF_SLUG} == main ]]; then
            echo "IMAGE_TAG=prod" >> $GITHUB_ENV
            echo "IMAGE_NAMES=${{ env.REGISTRY_NAME }}/github-actions-docker-sample:latest,${{ env.REGISTRY_NAME }}/github-actions-docker-sample:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${GITHUB_REF_SLUG}" >> $GITHUB_ENV
            echo "IMAGE_NAMES=${{ env.REGISTRY_NAME }}/github-actions-docker-sample:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV
          fi

      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Docker Login
        uses: docker/login-action@v1.13.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          logout: true
    
      - name: Build and push Docker images
        if: ${{ github.ref == 'refs/heads/stage' || github.ref == 'refs/heads/beta' }}
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          tags: ${{ env.IMAGE_NAMES }}
          file: build/Dockerfile.test
          push: true

#       - name: Build and push Docker images with Latest
#         if: ${{ github.ref == 'refs/heads/main' }}
#         uses: docker/build-push-action@v2.9.0
#         with:
#           context: .
#           tags: ${{ env.REGISTRY_NAME }}/github-actions-docker-sample:latest, ${{ env.REGISTRY_NAME }}/github-actions-docker-sample:${{ env.IMAGE_TAG }}
#           file: build/Dockerfile.test
#           push: true
          
