name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '40 4 * * *'
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Print Directory
        run: | 
          pwd
          ls -al
          echo ${{ secrets.DOCKERHUB_LOGIN }}
    
#       - name: Docker Login
#         uses: docker/login-action@v1.13.0
#         with:
#           # Username used to log against the Docker registry
#           username: 
#           # Password or personal access token used to log against the Docker registry
#           password: # optional
#           logout: # optional, default is true
    
#       - name: Build and push Docker images
#         uses: docker/build-push-action@v2.9.0
#         with:
#           context: .
#           file: build/Dockerfile.test
#           push: false
          
          
