name: CI/CD

on:
  push:
    branches: [ main, stage, beta ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main, stage, beta ]

env:
  # github.repository as <account>/<repo>
  REGISTRY_NAME: macnev


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Setup Docker Image Tags
        id: prep
        run: |
          if [ ${GITHUB_REF_SLUG} == "main" ] ; then
            TAGS="${REGISTRY_NAME}/github-actions-docker-sample:latest","${REGISTRY_NAME}/github-actions-docker-sample:prod"
            TEST="test-var"
          else
            TAGS="${REGISTRY_NAME}/github-actions-docker-sample:${GITHUB_REF_SLUG}"
          fi
          echo "::set-output name=IMAGE_TAGS::${TAGS}, name=TEST_VAR::${TEST}"
          
      - name: Checkout
        uses: actions/checkout@v2.4.0
        
      - name: Var
        run : |
          echo ${{ steps.prep.outputs.IMAGE_TAGS }}

      - name: Docker Login
        uses: docker/login-action@v1.13.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          logout: true
    
      - name: Build and push Docker images
        if: ${{ github.ref == 'refs/heads/stage' || github.ref == 'refs/heads/beta' || github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          tags: ${{ steps.prep.outputs.IMAGE_TAGS }}
          file: build/Dockerfile.test
          push: true
