name: CI/CD

on:
  push:
    branches: [ main, stage, beta ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main, stage, beta ]

env:
  # github.repository as <account>/<repo>
  REGISTRY_NAME: macnev


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Sets env vars for main branch
        run: |
          echo "DOCKER_IMAGE_TAG=prod" >> $GITHUB_ENV
        if: ${{ github.ref == 'refs/heads/main' }}

      - name: Sets env vars for other branch
        run: |
          echo "DOCKER_IMAGE_TAG=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')" >> $GITHUB_ENV
        if: ${{ github.ref == 'refs/heads/stage' || github.ref == 'refs/heads/beta' }}
    
      - name: Docker Login
        uses: docker/login-action@v1.13.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          logout: true
    
      - name: Build and push Docker images
        if: ${{ github.ref == 'refs/heads/stage' || github.ref == 'refs/heads/beta' }}
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          tags: ${{ env.REGISTRY_NAME }}/github-actions-docker-sample:${{ env.DOCKER_IMAGE_TAG }}
          file: build/Dockerfile.test
          push: true

      - name: Build and push Docker images with Latest
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          tags: ${{ env.REGISTRY_NAME }}/github-actions-docker-sample:latest, ${{ env.REGISTRY_NAME }}/github-actions-docker-sample:${{ env.DOCKER_IMAGE_TAG }}
          file: build/Dockerfile.test
          push: true
          
