name: CI/CD
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ main, stage ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main, stage ]

env:
  # github.repository as <account>/<repo>
  REGISTRY_NAME: macnev


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Extract branch name
        run: |
          echo "DOCKER_IMAGE_NAME=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/heads/*')

      - name: Print Directory
        run: | 
          pwd
          ls -al
          echo ${{ env.DOCKER_IMAGE_NAME }}
    
      - name: Docker Login
        uses: docker/login-action@v1.13.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          logout: true
    
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          tags: ${{ env.REGISTRY_NAME }}/github-actions-docker-sample:latest,${{ env.REGISTRY_NAME }}/github-actions-docker-sample:${{ env.DOCKER_IMAGE_NAME }}
          file: build/Dockerfile.test
          push: true
          
          
