name: Release-test

on:
  push:
    branches: [ release ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - run: gh auth status
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
